name: Node setup
description: "Sets up the environment for jobs using node"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        package_json_file: "./ui/package.json"
        run_install: |
          - cwd: "ui"

    - uses: actions/setup-node@v3
      with:
        node-version-file: "./ui/.nvmrc"
        cache: "pnpm"
        cache-dependency-path: ui/pnpm-lock.yaml

    - name: install deps
      shell: bash
      run: cd ui && pnpm install --frozen-lockfile
